### ISSUE TITLE
Hello,  Dr. Vu ! Can you teach me how to use this tool transformer-lm? What command parameters should I use to use this tool? Can you tell me the relevant tutorials? Sorry to bother you.

### ISSUE THREAD

**Issue by Sawndip** [duyvuleo/Transformer-DyNet#1]
https://github.com/duyvuleo/Transformer-DyNet/blob/cffbafb97f792dc1b523b7d9020f0f5c0ed5e08f/src/transformer-lm.cc#L492

**Comment by Sawndip** [comment]
And when I called the function  initialise_params_from_file( ) of this code line , it is found that the function called is problematic and can not load the model.

**Comment by duyvuleo** [comment]
Hi @Sawndip : you have to train the model first before being able to use it for sampling. 

You may use the following command line:

```
mkdir  <your_folder>/model
nice ./build_gpu/transformer-lm --max-seq-len 100 --minibatch-size 1024 --treport 512 --dreport 20000 --vocab <vocab_file> -t <training_data_file> -d <dev_data_file> -p <your_folder>/model -e 100 --lr-eta 0.1 --lr-patience 10 --patience 20 --lr-eta-decay 2 --emb-dropout-p 0.1 --sublayer-dropout-p 0.1 --attention-dropout-p 0.1 --ff-dropout-p 0.1 --ff-activation-type 1 --nlayers 4 --num-units 512 --num-heads 4 --use-label-smoothing --label-smoothing-weight 0.1 --position-encoding 2 --reset-if-stuck --use-smaller-minibatch --num-resets 5 &><your_folder>/model/train.log &
```

Note that: <training_data_file> and <dev_data_file> have to be created by ./scripts/wrap-data.py as follows:
```
./scripts/wrap-data.py <train_file> <dev_file> <test_file> [<vocab_file>|<word_cutoff_freq>]
```
--vocab <vocab_file> can be used if you already have the existing vocabulary file, otherwise ignore it.
